# # -*- coding: utf-8 -*-
# """regex.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/17H-1k6yNy8bscUirxB_WcY8heasQMpf5
# """

# print("skj")

# print("skj",end=" ")
# print("E3")

# # comment (documentation => kt)
# # python is a dynamic type programming

# x=100
# print(type (x))

# gender1="m"
# gender2='m'
# print (type (gender1),type (gender2))

# #string formating
# company ="regex"
# print("my company is",company)
# print(f"my company is {company}")

# #operators => symbol to perform specific task
# # 1. ARTHEMATIC OPERATOR

# print(100//3) #floor division
# print (5.0+2) # float + int -> float
# print(11%3) #mod -> remainder
# print(2**3**2) # 3**2 then 2**9 => 512
# print (10+2*4/2-7+6)
# # ** , [* / // %],+ -

# # relational operator => < ,>, <=,>=,!=,==
# # logical operator =>
# print (10>2 and 2>3)
# print (10>2 or 2>3)

# # membership operator
# print("j" in "JAIPUR")
# print("T" not in "JAIPUR")

# # conditional statement
# print ("hello") # it always run
# # but i want to run in some condition so we use conditional statement
# if (True):
#   print("hello") # IT ONLY RUN WHEN CONDITION IS TRUE

# print("GO!!") # IT ALWAYS RUN

# print("=> if else statement")
# if (True):
#   print("hello")
# else:
#   print("hy!!")

# print("GO!!")

# print("=> even or odd number : ")
# num=10
# if (num% 2==0):
#   print(f"{num} is even ")
# else :
#   print(f"{num} is odd ")

# print("=>is number divided by 6 : ")
# num=10
# if (num% 2==0 and num%3==0):
#   print(f"{num} is divisible by 6 ")
# else :
#   print(f"{num} is not divisible by 6 ")

# print("=>is number divided by 2 or 3 or not by any one : ")
# num=10
# if (num% 2==0):
#   print(f"{num} is divisible by 2 ")
# elif (num% 3==0):
#   print(f"{num} is divisible by 3 ")
# else :
#   print(f"{num} is not divisible 2 nor by 3 ")

# # take 3 variable a,b,c and find the minimum value
# a=int(input(" enter the value of a : "))
# b=int(input(" enter the value of b : "))
# c=int(input(" enter the value of c : "))
# if (a>b and a>c):
#   if(b>c):
#      print(f"{c} is minimum number")
#   else:
#     print(f"{b} is minimum number")
# else:
#   print(f"{a} is minimum number")

# # age >18 -> adult,age> 25 married,age>60 senior citizen,otherwise children
# age = int(input(" enter the value of age : "))
# if (age >60):
#   print("senior citizen!")
# elif(age>25):
#   print("married")
# elif(age>18):
#   print("adult")
# else:
#   print ("ara mera bacha!!")

# # nested if else
# # num => 6 (2 and 3)
# num=12
# if (num%2==0):
#   if("num %3 ==0"):
#     print("DIVIDED BY 2 AND 3 i.e. DIVIDED BY 6")
#   else:
#     print("DIVIDED BY 2")

# else:
#   print("NOT DIVIDED BY 6 AT ALL")

# # STRING INDEXING AND SLICING
# '''
# <---------
#        -1
# RAJASTHAN
# 012345678
# ---------->

# '''
# state="RAJASTHAN"
# print (state[1])
# print (state[-1])

# using the python prog do the following task ...
# 1) take a input from a user ,if the user give 1 as a input then create a folder on the desktop , if a user give a user give input 2 then create a file on desktop, if a user give a input 3 then give WhatsApp msg to friend , if input 4 shut down the pc
import os
import pywhatkit as pyw
print("1. YOU WANT TO CREATE THE FOLDER ")
print("2. CREATE FILE ON DESKTOP ")
print("3. whatsapp to the friend number")
print("4. shut down the pc")

user_choice=int(input("ENTER THE CHOICE : "))

if (user_choice==1):
  folder_name=input("ENTER THE FOLDER NAME : ")
  path=f"D:/REGEX/DAY_1/{folder_name}"
  os.mkdir(path)

elif(user_choice==2):
  file_name=input("ENTER THE FILE NAME : ")
  Message=input("ENTER THE MESSAGE TO WRITE IN THE FILE : ")
  path=f"C:/Users/Dell/Desktop/{file_name}.txt"
  with open(path,"w") as f:
    f.write(f"{Message}")

elif(user_choice==3):
  phone = input("ENTER THE PHONE NUMBER TO WHOM YOU SEND: ")
  if phone.isdigit() and len(phone) == 10:
      PHONE_NO = f"+91{phone}"
      MESSAGE = input("ENTER THE WHATSAPP MESSAGE: ")
      
      try:
          pyw.sendwhatmsg_instantly(PHONE_NO, MESSAGE, wait_time=15, tab_close=True)
          print("Message sent successfully!")
      except Exception as e:
          print("An error occurred:", e)
  else:
      print("YA WRONG NUMBER HA!!")

    
elif(user_choice==4):
  conform=(input("YOU WANT TO SHUTDOWN THE PC \n YES / NO : ")).lower()
  if(conform=="yes"):
   os.system("shutdown /s /t 0")
  else:
    print("INVALID INPUT!!")
else:
  print("ENTER THE CORRECT CHOICE!")

